### ISSUE TITLE
All  setCustomTransactionAnimation

### ISSUE THREAD

**Issue by carmas123** [Fueled/flowr#12]
Please can you add also overloaded method

    public abstract FragmentTransaction setCustomAnimations(@AnimRes int enter,
            @AnimRes int exit);

>     public abstract FragmentTransaction setCustomAnimations(@AnimRes int enter,
>             @AnimRes int exit, @AnimRes int popEnter, @AnimRes int popExit);

**Comment by julien-fueled** [comment]
@carmas123 thank you for your feedback, we are looking into and will get back to you

**Comment by julien-fueled** [comment]
@carmas123 we have integrated the changes to version `1.1.1`.
