### ISSUE TITLE
Problem with Stacked Fragment

### ISSUE THREAD

**Issue by carmas123** [Fueled/flowr#14]
When you use a fragments with 
`.skipBackStack(false)` and `.clearBackStack(false)` the previous fragment will not replaced and stay active back to the current fragment.
This fragment need to be hidden otherwise with Toolbar and menu we have many problems.
If you create a simple activity with a toolbar and call `supportInvalidateOptionsMenu` each you create a new fragment to update the toolbar menu, the event `onCreateOptionsMenu` will be called for each stacked fragment.

Sorry for my english.

**Comment by hussein-fueled** [comment]
Hi @carmas123, to replace the previous fragment you can call `.replaceCurrentFragment(true)` when displaying your next fragment.

**Comment by carmas123** [comment]
Yes this is true, but if you display a fragment with animation and use `replaceCurrentFragment(true)` the previous fragment become hidden even before the animation is over.
