### ISSUE TITLE
Navigation Drawer Sample

### ISSUE THREAD

**Issue by bansawbanchee** [Fueled/flowr#18]
What would be nice is a sample of using the drawer. I've pretty much been winging it and looking at the FlowrFragment class to get an understanding of how it works.

I am still not sure how it works entirely or if I am even doing it right.

**Comment by hussein-fueled** [comment]
@bansawbanchee thank you for your feedback, we will work on adding that to the sample app.

**Comment by hussein-fueled** [comment]
Hi @bansawbanchee, we've updated our sample app to include support for the navigation drawer. Hopefully this will provide a clearer picture of how everything is integrated together.
