### ISSUE TITLE
Kotlin gradle compatibility

### ISSUE THREAD

**Issue by carmas123** [Fueled/flowr#30]
With Kotlin in Gradle is not needed to use "annotationProcessor" but simple "kapt"
With yout lastest version 1.4.0 when I try to use kapt with 
`kapt 'com.github.fueled.flowr:flowr-compiler:1.4.0'`

I got an exception: 

> Error:Execution failed for task ':myproject:javaPreCompileMainDebug'.
> > Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
>     - flowr-compiler-1.4.0.jar (com.github.fueled.flowr:flowr-compiler:1.4.0)
>   Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
>   See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

Please can you investigate to solve this problem?

I cannot mix kapt and annotaionProcessor into my gradle because it cause a problem with Parceler library.

Thank you

**Comment by v3n3** [comment]
@carmas123 thank you for your feedback. We are currently reviewing it and will get back to you as soon as we have something

**Comment by v3n3** [comment]
@carmas123 i try to reproduce the bug on my end but to no result. Can you share with us your `build.gradle` file?

**Comment by v3n3** [comment]
I am closing this issue because it became stale.
