### ISSUE TITLE
flowr should default to noTransactionAnimation

### ISSUE THREAD

**Issue by esoxjem** [Fueled/flowr#39]
Currently, `flowr` provides entry and exit custom transitions by default which causes us to use `noTransactionAnimation()` a lot. Instead we could switch the default behaviour. Thoughts @husseinala?

**Comment by husseinala** [comment]
@esoxjem you actually don't need to use `noTransactionAnimation()` if you haven't provided default enter/exit animations by extending `Flowr` and overriding any of these methods `getDefaultEnterAnimation()`, `getDefaultExitAnimation()`, `getDefaultPopEnterAnimation()`, or `getDefaultPopExitAnimation()`.

**Comment by esoxjem** [comment]
@ragdroid @chetdeva @initishbhatt looks it defaults to no animation 🤔 We don't need to add it. Good to close?

**Comment by chetdeva** [comment]
Yes 👍
