### ISSUE TITLE
Add events to show/hide fragments

### ISSUE THREAD

**Issue by Amenocy** [Fueled/flowr#6]
hello 
thank you for your work.
can you please add events to fragments called when fragment is show/hide ? 
for example when new fragment displayed , fire event in old fragment "onHide()" 
when back button pressed and fragment onDestroy called , fire event on backstack fragment "onShow"

**Comment by hussein-fueled** [comment]
Hi @Amenocy, Thanks for testing out the library!  

We will look into adding these changes in a future release.

**Comment by julien-fueled** [comment]
@Amenocy those hooks are  now available in release 1.1.0. You should be able to implement/override 2 event listener `onShown` and `onHidden`.
